[package]
name = "rsparse"
version = "0.1.0"
authors = ["Ricard Lado"]
edition = "2021"
description = "This crate provides a simple library for solving sparse linear systems using direct methods implemented in Rust."
readme = "README.md"
repository = "https://github.com/rlado/rsparse"
license = "GPL-3.0-only"

[dependencies]
